# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(296, 136)
        MainWindow.setWindowOpacity(0.9)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.filepath = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.filepath.setObjectName("filepath")
        self.gridLayout.addWidget(self.filepath, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.browse = QtWidgets.QPushButton(parent=self.centralwidget)
        self.browse.setObjectName("browse")
        self.gridLayout.addWidget(self.browse, 1, 2, 1, 1)
        self.encrypt = QtWidgets.QPushButton(parent=self.centralwidget)
        self.encrypt.setObjectName("encrypt")
        self.gridLayout.addWidget(self.encrypt, 2, 2, 1, 1)
        self.password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 3)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PDF File Protector"))
        self.label.setText(_translate("MainWindow", "File to encrypt"))
        self.label_2.setText(_translate("MainWindow", "Password"))
        self.browse.setText(_translate("MainWindow", "Browse..."))
        self.encrypt.setText(_translate("MainWindow", "ENCRYPT!"))
        self.label_3.setText(_translate("MainWindow", "PDF FILE PROTECTOR"))
